-- MySQL Script generated by MySQL Workbench
-- Tue Jul  1 10:51:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema segurosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema segurosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `segurosdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `segurosdb` ;

-- -----------------------------------------------------
-- Table `segurosdb`.`beneficiaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`beneficiaries` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`beneficiaries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `relationship` VARCHAR(50) NULL DEFAULT NULL,
  `percentage` DECIMAL(5,2) NOT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `identification_number` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `contract_id` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `beneficiaries_ibfk_1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `segurosdb`.`client_policies` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 92
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`claims`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`claims` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`claims` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `policy_id` INT NOT NULL,
  `claim_date` DATE NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `status` ENUM('submitted', 'approved', 'rejected') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'submitted',
  `processed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `policy_id` (`policy_id` ASC) VISIBLE,
  CONSTRAINT `claims_ibfk_1`
    FOREIGN KEY (`policy_id`)
    REFERENCES `segurosdb`.`policies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`client_policies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`client_policies` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`client_policies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `policy_id` INT NOT NULL,
  `agent_id` INT NOT NULL,
  `premium_amount` DECIMAL(10,2) NOT NULL,
  `payment_frequency` VARCHAR(20) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `extra_data` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `policy_id` (`policy_id` ASC) VISIBLE,
  INDEX `agent_id` (`agent_id` ASC) VISIBLE,
  CONSTRAINT `client_policies_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `segurosdb`.`clients` (`id`),
  CONSTRAINT `client_policies_ibfk_2`
    FOREIGN KEY (`policy_id`)
    REFERENCES `segurosdb`.`policies` (`id`),
  CONSTRAINT `client_policies_ibfk_3`
    FOREIGN KEY (`agent_id`)
    REFERENCES `segurosdb`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 114
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`client_policies_backup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`client_policies_backup` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`client_policies_backup` (
  `id` INT NOT NULL DEFAULT '0',
  `client_id` INT NOT NULL,
  `policy_id` INT NOT NULL,
  `agent_id` INT NOT NULL,
  `premium_amount` DECIMAL(10,2) NOT NULL,
  `payment_frequency` VARCHAR(20) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `extra_data` JSON NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`client_policy_extra_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`client_policy_extra_data` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`client_policy_extra_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` INT NOT NULL,
  `field_name` VARCHAR(64) NOT NULL,
  `field_value` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `contract_id` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `client_policy_extra_data_ibfk_1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `segurosdb`.`client_policies` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 499
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`clients` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `last_name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `phone` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `agent_id` INT NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'inactivo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `clients_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `segurosdb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`documents` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` INT NOT NULL,
  `doc_type` VARCHAR(50) NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `uploaded_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `uploaded_by` ENUM('agente', 'cliente') NOT NULL DEFAULT 'cliente',
  `upload_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('pendiente', 'aprobado', 'rechazado') NULL DEFAULT 'pendiente',
  `reviewed_by` INT NULL DEFAULT NULL,
  `review_date` DATETIME NULL DEFAULT NULL,
  `review_comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `contract_id` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `documents_ibfk_1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `segurosdb`.`client_policies` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 200
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`documents_refunds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`documents_refunds` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`documents_refunds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `doc_type` VARCHAR(255) NULL DEFAULT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `uploaded_at` DATETIME NOT NULL,
  `uploaded_by` VARCHAR(100) NOT NULL,
  `upload_date` DATETIME NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `reviewed_by` VARCHAR(100) NULL DEFAULT NULL,
  `review_date` DATETIME NULL DEFAULT NULL,
  `review_comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `invoice_id` (`invoice_id` ASC) VISIBLE,
  INDEX `status` (`status` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`payments` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `policy_id` INT NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `payment_date` DATE NOT NULL,
  `method` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `status` ENUM('paid', 'due', 'failed') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'due',
  PRIMARY KEY (`id`),
  INDEX `policy_id` (`policy_id` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`policy_id`)
    REFERENCES `segurosdb`.`policies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`policies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`policies` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`policies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `client_id` INT NULL DEFAULT NULL,
  `agent_id` INT NULL DEFAULT NULL,
  `type_id` INT NOT NULL,
  `coverage_details` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `benefits` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `premium_amount` DECIMAL(12,2) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `status` ENUM('active', 'pending', 'cancelled', 'expired') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'pending',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `payment_frequency` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'Mensual',
  `insured_amount` DECIMAL(15,2) NULL DEFAULT '0.00',
  `payment_method` VARCHAR(50) NULL DEFAULT 'Tarjeta',
  PRIMARY KEY (`id`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `agent_id` (`agent_id` ASC) VISIBLE,
  INDEX `type_id` (`type_id` ASC) VISIBLE,
  CONSTRAINT `policies_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `segurosdb`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `policies_ibfk_2`
    FOREIGN KEY (`agent_id`)
    REFERENCES `segurosdb`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `policies_ibfk_3`
    FOREIGN KEY (`type_id`)
    REFERENCES `segurosdb`.`policy_types` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 110
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`policy_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`policy_types` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`policy_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `cost` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `payment_frequency` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'Mensual',
  `status` ENUM('Activo', 'Inactivo') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`refunds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`refunds` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`refunds` (
  `id` CHAR(36) NOT NULL,
  `policy_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `agent_id` INT NOT NULL,
  `request_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` DECIMAL(12,2) NOT NULL,
  `health_institution_name` VARCHAR(255) NULL DEFAULT NULL,
  `health_institution_type` ENUM('publica', 'privada') NULL DEFAULT NULL,
  `refund_type` ENUM('gastos_medicos', 'fallecimiento', 'discapacidad', 'otros') NULL DEFAULT NULL,
  `refund_type_other` VARCHAR(255) NULL DEFAULT NULL,
  `event_description` TEXT NULL DEFAULT NULL,
  `event_date` DATE NULL DEFAULT NULL,
  `payment_method` ENUM('transferencia_bancaria', 'cheque', 'otros') NULL DEFAULT NULL,
  `account_holder_name` VARCHAR(255) NULL DEFAULT NULL,
  `bank_account_number` VARCHAR(100) NULL DEFAULT NULL,
  `bank_name` VARCHAR(255) NULL DEFAULT NULL,
  `account_type` VARCHAR(50) NULL DEFAULT NULL,
  `swift_aba_code` VARCHAR(50) NULL DEFAULT NULL,
  `payment_method_other` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('pending', 'approved', 'rejected', 'processed') NOT NULL DEFAULT 'pending',
  `created_by` INT NOT NULL COMMENT 'Usuario que creó la solicitud',
  `processed_by` INT NULL DEFAULT NULL COMMENT 'Usuario que procesó la solicitud',
  PRIMARY KEY (`id`),
  INDEX `idx_refund_policy` (`policy_id` ASC) VISIBLE,
  INDEX `idx_refund_client` (`client_id` ASC) VISIBLE,
  INDEX `idx_refund_status` (`status` ASC) VISIBLE,
  INDEX `idx_refund_dates` (`request_date` ASC) VISIBLE,
  INDEX `fk_refund_agent` (`agent_id` ASC) VISIBLE,
  INDEX `fk_refund_created_by` (`created_by` ASC) VISIBLE,
  INDEX `fk_refund_processed_by` (`processed_by` ASC) VISIBLE,
  CONSTRAINT `fk_refund_agent`
    FOREIGN KEY (`agent_id`)
    REFERENCES `segurosdb`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_refund_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `segurosdb`.`clients` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_refund_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `segurosdb`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_refund_policy`
    FOREIGN KEY (`policy_id`)
    REFERENCES `segurosdb`.`policies` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_refund_processed_by`
    FOREIGN KEY (`processed_by`)
    REFERENCES `segurosdb`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`roles` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `segurosdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segurosdb`.`users` ;

CREATE TABLE IF NOT EXISTS `segurosdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `role_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `segurosdb`.`roles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 164
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
