version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: seguros_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE:    ${DB_NAME}
      MYSQL_USER:        ${DB_USER}
      MYSQL_PASSWORD:    ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: seguros_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app    # Permite recarga en caliente en desarrollo

volumes:
  db_data:
